### ISSUE TITLE
Add Support for chipKIT-PGM Programmer?

### ISSUE THREAD

**Issue by rei-vilo** [sergev/ejtagproxy#5]
The chipKIT-PGM  is sold by Digilent Inc. at https://store.digilentinc.com/chipkit-pgm-programmer-debugger-for-use-with-digilent-chipkit-platforms/

It works with the MPLAB® and MPLAB® X development environments available from Microchip.

**Comment by sergev** [comment]
The chipKIT-PGM is basically an OEM version of picKIT3 programmer. Unfortunately, it uses a proprietary protocol, which is pretty complicated, and Microchip has no intention to disclose the details.

**Comment by rei-vilo** [comment]
Thanks!
